---

- name: configure canvas cache store
  template: src=cache_store.yml.j2 dest=/home/deploy/canvas/{{ application }}/shared/config/cache_store.yml
  notify: restart nginx service
  tags: canvas

- name: create a symlink cache store
  shell: "ln -s {{ shared_path }}/config/cache_store.yml {{ release_path }}/first/config/cache_store.yml"
  tags: symlink