---

- name: create a symlink current
  shell: "ln -s {{ release_path }}/first /home/deploy/canvas/{{ application }}/current"
  #when: not canvas_installed.stat.exists
  tags: symlink

- name: check if canvas gems are installed
  stat: path={{ my_path }}/releases/first/vendor/bundle
  register: canvas_gems_installed
  tags:
    - canvas
    - gems

- name: create the link to node_modules
  command: "ln -s {{ my_path }}/shared/node_modules {{ release_path }}/first/node_modules"
  tags:
    - canvas
    - gems

- name: create a symlink ooor
  shell: "ln -s {{ shared_path }}/config/ooor.yml {{ release_path }}/first/config/ooor.yml"
  tags: symlink

- name: make the folder usable by deploy user
  sudo: yes
  command: sudo chown deploy:deploy -R /home/deploy/canvas/
  tags: canvas installation

# - name: make the ruby folder readable for all users
#   sudo: yes
#   command: chmod 777 -R /home/deploy/lib/gems/2.1.0
#   tags: canvas installation

- name: install bundler gem
  sudo: yes
  command: "chdir={{ release_path }}/first gem install bundler --version=1.7.10"
  when: not canvas_gems_installed.stat.exists
  tags:
    - canvas
    - gems
  sudo_user: '{{ rvm1_user }}'
  ignore_errors: True

# `test` would be excluded, however it is needed to compile assets locally.

- name: bundle install
  sudo_user: "{{ user }}"
  command: "chdir={{ release_path }}/first bundle install --path vendor/bundle --deployment"
  notify: restart apache service
  when: not canvas_gems_installed.stat.exists
  tags:
    - canvas
    - gems
  ignore_errors: True

- name: remove id_rsa
  sudo: yes
  command: rm -rf dest=/root/.ssh/id_rsa
  tags: canvas download