---

- name: configure canvas rdb
  template: src=database.yml.j2 dest=/home/deploy/canvas/{{ application }}/shared/config/database.yml
  notify: restart nginx service
  tags: canvas

- name: create a symlink database
  shell: "ln -s {{ shared_path }}/config/database.yml {{ release_path }}/first/config/database.yml"
  tags: symlink
