---

- name: configure canvas session store
  template: src=session_store.yml.j2 dest=/home/deploy/canvas/{{ application }}/shared/config/session_store.yml
  notify: restart nginx service
  tags: canvas

- name: create a symlink session_store
  shell: "ln -s {{ shared_path }}/config/session_store.yml {{ release_path }}/first/config/session_store.yml"
  tags: symlink