---

- name: configure canvas security
  template: src=security.yml.j2 dest=/home/deploy/canvas/{{ application }}/shared/config/security.yml
  notify: restart nginx service
  tags: canvas

- name: create a symlink security
  shell: "ln -s {{ shared_path }}/config/security.yml {{ release_path }}/first/config/security.yml"
  tags: symlink