---

- name: configure canvas file store
  template: src=file_store.yml.j2 dest=/home/deploy/canvas/{{ application }}/shared/config/file_store.yml
  notify: restart nginx service
  tags: canvas

- name: create a symlink file_store
  shell: "ln -s {{ shared_path }}/config/file_store.yml {{ release_path }}/first/config/file_store.yml"
  tags: symlink