---

- name: check if canvas gems are installed
  stat: path=/var/canvas/{{ application }}/vendor/bundle
  register: canvas_gems_installed
  tags:
    - canvas
    - gems

- name: make the folder usable by deploy user
  sudo: yes
  command: sudo chown deploy:deploy -R /var/canvas/
  tags: canvas installation

# - name: make the ruby folder readable for all users
#   sudo: yes
#   command: chmod 777 -R /var/lib/gems/2.1.0
#   tags: canvas installation

- name: install bundler gem
  sudo: yes
  command: sudo gem install bundler --version=1.7.10
  when: not canvas_gems_installed.stat.exists
  tags:
    - canvas
    - gems
  sudo_user: '{{ rvm1_user }}'

# `test` would be excluded, however it is needed to compile assets locally.
- name: install canvas gems
  command: chdir=/var/canvas/{{ application }}/releases/first bundle install --path vendor/bundle --without=sqlite mysql development ooor
  notify: restart nginx service
  when: not canvas_gems_installed.stat.exists
  tags:
    - canvas
    - gems