---

- name: check if canvas node modules are installed
  stat: 'path={{ my_path }}/releases/first/node_modules'
  register: canvas_node_modules_installed
  tags:
    - canvas
    - node_modules

# - name: install canvas node modules
#   command: "chdir={{ my_path }}/releases/first npm install"
#   notify: restart nginx service
#   when: not canvas_node_modules_installed.stat.exists
#   tags:
#     - canvas
#     - node_modules
#   ignore_errors: True