---

- name: configure canvas outgoing mail
  template: src=outgoing_mail.yml.j2 dest=/home/deploy/canvas/{{ application }}/shared/config/outgoing_mail.yml
  notify: restart nginx service
  tags: canvas

- name: create a symlink outgoing email
  shell: "ln -s {{ shared_path }}/config/outgoing_mail.yml {{ release_path }}/first/config/outgoing_mail.yml"
  tags: symlink