---

- name: compile canvas assets
  shell: "chdir={{current_path}} bundle exec rake canvas:compile_assets"
  notify: restart nginx service
  #when: not canvas_installed.stat.exists
  tags:
    - canvas
    - assets
  ignore_errors: True


- name: create require repos
  shell: 'chdir={{current_path}} mkdir -p log tmp/pids public/assets public/stylesheets/compiled'

- name: touch the lock
  shell: 'chdir={{current_path}} touch Gemfile.lock'

- name: copy canvas_init script
  copy: src=etc/init.d/canvas_init dest=/etc/init.d/canvas_init owner=root group=root mode=755
  when: (background_jobs_only is defined and background_jobs_only|bool) or (background_jobs is defined and background_jobs|bool)
  tags: canvas

- name: create canvas background jobs daemon
  command: update-rc.d canvas_init defaults creates=/etc/rc0.d/K20canvas_init
  when: (background_jobs_only is defined and background_jobs_only|bool) or (background_jobs is defined and background_jobs|bool)
  tags: canvas

- name: enable canvas background jobs daemon
  service: name=canvas_init state=started enabled=yes
  when: (background_jobs_only is defined and background_jobs_only|bool) or (background_jobs is defined and background_jobs|bool)
  tags: canvas

- name: check if canvas qti is installed
  stat: 'path={{ shared_path }}/vendor/QTIMigrationTool'
  register: canvas_qti_installed
  tags:
    - canvas
    - qti

- name: git clone qti
  git:
    'repo=https://github.com/instructure/QTIMigrationTool.git
    dest={{ shared_path }}/vendor/QTIMigrationTool'
  when: not canvas_qti_installed.stat.exists
  tags:
    - canvas
    - qti

- name: chmod canvas qti
  command: 'chmod +x {{ shared_path }}/vendor/QTIMigrationTool/migrate.py'
  notify:
    - restart nginx service
    - restart canvas_init service
  when: not canvas_qti_installed.stat.exists
  tags:
    - canvas
    - qti

- name: Detect canvasuser
  stat: path=/home/canvasuser
  register: canvasuser

- name: secure /home/deploy/canvas 1
  sudo: yes
  command: "adduser --disabled-password --gecos canvas canvasuser "
  when: not canvasuser.stat.exists
  tags: canvas

- name: secure /home/deploy/canvas 2
  sudo: yes
  command: "chown canvasuser /home/deploy/canvas/{{ application }}/shared/config/*.yml"
  tags: canvas

- name: secure /home/deploy/canvas/config
  sudo: yes
  shell: "chmod 400 /home/deploy/canvas/{{ application }}/shared/config/*.yml"
  tags: canvas
  ignore_errors: True
