---
- name: check if canvas is installed
  stat: path=/home/deploy/canvas
  register: canvas_installed
  tags: canvas download


# This is mainly for capistrano later since sudo is no longer available in v3
- name: create sudoers file
  sudo: yes
  template: src=sudoers.j2 dest=/etc/sudoers.d/{{ user }}_appservers_lms validate='visudo -cf %s' owner=root group=root mode=0440

- name: create canvas directories
  file: path={{ item }} state=directory
  with_items:
    - '/home/deploy/canvas'
    - '{{ my_path }}'
    - '{{ my_path }}/shared'
    - '{{ my_path }}/shared/log'
    - '{{ my_path }}/releases'
    - '{{ my_path }}/shared/tmp/pids'
    - '{{ my_path }}/shared/public/assets'
    - '{{ my_path }}/shared/public/stylesheets/compiled'
    - '{{ my_path }}/shared/config'
    - '{{ my_path }}/shared/node_modules'
  tags: canvas download

#This assume that you already have rbenv install
# - name: "Install {{ ruby_version }}"
#   command: "sudo -iu {{ rbenv_user }} rbenv install {{ ruby_version }}"
#   tags: rbenv
#   ignore_errors: True

# - name: "Install the bundler"
#   command: 'RBENV_ROOT=~/.rbenv RBENV_VERSION={{ ruby_version }} ~/.rbenv/bin/rbenv exec gem install bundler'
#   tags: set up bundler with the require ruby version
#   ignore_errors: True

- include: unicorn.yml
