---
- name: check if canvas is installed
  stat: path=/var/canvas
  register: canvas_installed
  tags: canvas download


# This is mainly for capistrano later since sudo is no longer available in v3
- name: create sudoers file
  sudo: yes
  template: src=sudoers.j2 dest=/etc/sudoers.d/{{ user }}_appservers validate='visudo -cf %s' owner=root group=root mode=0440

- name: create canvas directories
  file: path={{ item }} state=directory
  with_items:
    - /var/canvas
    - /var/canvas/{{ application }}
    - /var/canvas/{{ application }}/shared
    - /var/canvas/{{ application }}/shared/log
    - /var/canvas/{{ application }}/releases
    - /var/canvas/{{ application }}/shared/tmp/pids
    - /var/canvas/{{ application }}/shared/public/assets
    - /var/canvas/{{ application }}/shared/public/stylesheets/compiled
    - /var/canvas/{{ application }}/shared/config
  tags: canvas download

- include: unicorn.yml
