---

- name: update postgresql authentication type
  sudo: yes
  template: src=pg_hba.conf.j2 dest=/etc/postgresql/{{ postgres_version }}/main/pg_hba.conf owner=postgres group=postgres mode=0600
  notify: restart postgresql

- meta: flush_handlers # We need to run this handler so the auth methods are relaxed

# - name: create postgres user
#   postgresql_user: login_host=localhost name={{ user }} password={{ postgresql_password }} fail_on_user=yes state=present role_attr_flags=CREATEDB,SUPERUSER

# - name: create 1st database for production
#   sudo: yes
#   postgresql_db: name={{ first_db_name }} owner={{ user }} state=present login_host=localhost

# - name: reate 2nd database for production queue
#   sudo: yes
#   postgresql_db: name={{ second_db_name }} owner={{ user }} state=present login_host=localhost

- name: create hstore extension
  command: psql -U postgres -c "create extension if not exists hstore;"

- name: update postgresql authentication type to safe settings
  sudo: yes
  template: src=pg_hba_safe.conf.j2 dest=/etc/postgresql/{{ postgres_version }}/main/pg_hba.conf owner=postgres group=postgres mode=0600
  notify: restart postgresql

- name: update postgresql.conf to allow tcp connections
  sudo: yes
  lineinfile: dest=/etc/postgresql/{{ postgres_version }}/main/postgresql.conf regexp='^listen_addresses' line="listen_addresses = '*'" state=present
  notify: restart postgresql
