- name: install nginx related packages
  sudo: yes
  apt: pkg=nginx state=latest update_cache=yes cache_valid_time=3600
  tags: nginx

# Assumes wildcard SSL if file store is `local`.
- name: copy canvas ssl public key
  sudo: yes
  copy: src=server.crt.j2 dest=/etc/ssl/server.crt owner=root group=root mode=644
  notify: restart nginx service
  tags:
    - nginx
    - ssl

# Assumes wildcard SSL if file store is 'local'.
- name: copy canvas ssl private key
  sudo: yes
  copy: src=server.key.j2 dest=/etc/ssl/server.key owner=root group=root mode=640
  notify: restart nginx service
  tags:
    - nginx
    - ssl

- name: create canvas nginx cache
  sudo: yes
  file: path=/var/cache/nginx/canvas state=directory owner=www-data group=www-data mode=0755
  notify: restart nginx service
  tags: nginx

- name: remove default nginx sites
  sudo: yes
  file: path={{ item }} state=absent
  with_items:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/sites-available/default
  notify: restart nginx service
  tags: nginx

- name: configure nginx
  sudo: yes
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: restart nginx service
  tags: nginx

- name: configure canvas nginx site
  sudo: yes
  template: src=sites-available/canvas.j2 dest=/etc/nginx/sites-available/canvas
  notify: restart nginx service
  tags: nginx

- name: configure canvas-unavailable nginx site
  sudo: yes
  template: src=sites-available/canvas-unavailable.j2 dest=/etc/nginx/sites-available/canvas-unavailable
  notify: restart nginx service
  tags: nginx

- name: enable canvas nginx site
  sudo: yes
  file: src=/home/deploy/ansible_script_for_canvas_production/roles/web/files/canvas.j2 dest=/etc/nginx/sites-enabled/canvas state=link
  notify: restart nginx service
  tags: nginx

- name: create nginx monit file
  sudo: yes
  template: src=monit.conf.j2 dest=/etc/monit/conf.d/nginx.conf owner=root mode=0600